config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
 
   devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   get 'my_portfolio', to: 'users#my_portfolio'
   root "welcome#index"
   get 'search_stock', to: 'stocks#search'
   get 'my_friends', to: 'users#my_friends'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks
    
    validates :name, :ticker, presence: true

    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
            secret_token: Rails.application.credentials.iex_client[:sandbox_secret_key],
            endpoint: 'https://sandbox.iexapis.com/v1'
          )
          begin
          new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name,last_price: client.price(ticker_symbol))
        rescue => exception
            return nil
        end

    end

    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def stock_already_tracked?(ticker_symbol)

    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?


  end



  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
    
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"

  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

    
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
         @tracked_stocks = current_user.stocks
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            #render json: @stock
            if @stock
                render 'users/my_portfolio'
            else
                flash[:alert] = "Please enter a valid symbol"
                redirect_to my_portfolio_path
            end
        else
            flash[:alert] = "Please enter the symbol"
            redirect_to my_portfolio_path
        end
    end
    
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
          stock = Stock.new_lookup(params[:ticker])
          stock.save
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
        redirect_to my_portfolio_path

    end

    def destroy
      stock = Stock.find(params[:id])
      user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id ).first
      user_stock.destroy
      flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
      redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

end

  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
  <footer class="footer mt-auto py-3 text-center">
    <div class="text-center   mt-2 text-light">
      © 2022 Copyright: All rights are reserved
    </div>
  </footer>

app/views/layouts/_messages.html.erb
<% if notice %>
    <p class="alert alert-success">
        <%= notice %>
    </p>
<% end %>

<% if alert %>
    <p class="alert alert-danger">
        <%= alert %>
    </p>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg nav-color">
    <div class="container-fluid">
        
        <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
        <% if current_user%>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
                       
                        <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
                    </li>
                  
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Profile
                        </a>
                        <ul class="dropdown-menu">
                            
                            <%= link_to 'Edit Profile', edit_user_registration_path,class: "dropdown-item"%>
                        
                        </ul>
                    </li>
                   
                </ul>
                <ul class = 'navbar-nav ml-auto'>
                    <li class='nav-item user-name'>
                        <%= fa_icon 'user' %><%= current_user.full_name%>
                    
                    </li>

                    <li class="nav-item ">
                        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: "btn btn-primary"%>
                    </li>


                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>

        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>FinanceTracker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
 
</head>

<body class = "bg">
  <%= render "layouts/navigation" %>
 
  <div class = "container">
    <%= render "layouts/messages" %>
    <%= yield %>
  </div>

   <%= render "layouts/footer" %>
</body>

</html>

app/views/users/_result.html.erb
<% if @stock %>

  <div class="card , d-inline-flex p-2">
    <div class="card-header">
      <strong>Symbol: </strong> <%= @stock.ticker %>
      <strong>Name: </strong> <%= @stock.name %>
      <strong>Price: </strong> <%= @stock.last_price %>
      <% if current_user.can_track_stock?(@stock.ticker)%>
        <%= button_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),method: :post %>
      <%else %>
        <span class="badge bg-info text-dark">
          
          You are already tracking
          <% if !current_user.under_stock_limit? %>
              10 stocks

          <% end %>

          <% if current_user.stock_already_tracked?(@stock.ticker)%>
            this stock

          <% end %>

        </span>

      <% end %>
    </div>

  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
  <h3>Search Stocks</h3>

  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class ="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      

      </div>
      <div class="col-sm-3 no-left-padding">
       <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <i class="fa fa-search fa-2x"></i>
               <% end %>
      </div>
    </div>

  <% end %>
</div>

<div id="results">
  <%= render 'users/result' %>
</div>
<% if !@tracked_stocks.empty? %>
  <div class = "row">
    <div class = "col-9">
          
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th scope="col">Ticker</th>
              <th scope="col">Name</th>
              <th scope="col">Price</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @tracked_stocks.each do |stock| %>
              <tr>
                <th scope="row"><%= stock.ticker %></th>
                <td><%= stock.name %></td>
                <td><%= stock.last_price %></td>
                <td><%= button_to 'Remove', user_stock_path(stock), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-primary btn-sm" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>


    </div>

  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Finance-Tracker App</h1>

<h2>Here we can search stocks and track them!!!</h2>

<br><h3> What is Stock Market ?
<p><br>
A stock market, equity market, or share market is the aggregation of buyers and sellers of stocks (also called shares), which represent ownership claims on businesses; these may include securities listed on a public stock exchange, as well as stock that is only traded privately, such as shares of private companies which are sold to investors through equity crowdfunding platforms. Investment is usually made with an investment strategy in mind.
</p>
</h3>

 <%= image_tag "download (1).jpeg", height: 140 %>
 <%= image_tag "download.jpeg", height: 140 %>
 <%= image_tag "download (2).jpeg", height: 140 %>
 <%= image_tag "images.jpeg", height: 140 %>
 <%= image_tag "images (1).jpeg", height: 140 %>